name: Receive PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update RIOT data
        run: make update_riot_data
        env:
          GITHUB_TOKEN: ${{ secrets.RIOT_CI_ACCESS_TOKEN }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.2'
          bundler-cache: true

      - name: Setup Environment
        run: |
          gem update --system 3.3.22
          gem install jekyll -v 4.2.2
          gem install bundler -v 2.4.22
          bundle install

      - name: Build
        run: make build

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/number

      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: |
            ./_site
            ./pr

