name: Receive PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update RIOT data
        run: make update_riot_data
        env:
          GITHUB_TOKEN: ${{ secrets.RIOT_CI_ACCESS_TOKEN }}

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Build
        uses: jerryjvl/jekyll-build-action@v1

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/number

      # push build to workflow artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: |
            ./_site
            ./pr
